version: "3"

tasks:
  default:
    desc: "List all available tasks"
    cmds:
      - task --list-all
  release-local:
    desc: "Release locally & copies to /usrlocal/bin"
    cmds:
      - goreleaser release --snapshot --clean --skip=publish
      - yes | cp dist/spartan_darwin_amd64_v1/spartan /usr/local/bin
    silent: true
